### ISSUE TITLE
Update on Python Package Index

### ISSUE THREAD

**Issue by greenfrogs** [marioidival/pyramid_mongoengine#3]
Is it possible to update the version which is on the [python package index](https://pypi.python.org/pypi/pyramid-mongoengine/0.0.4)?  As it still has the bug with ValidationError not being imported correctly.

**Comment by marioidival** [comment]
@greenfrogs yes, but you can install directy from github too...

example: pip install https://github.com/marioidival/pyramid_mongoengine/archive/master.zip

**Comment by greenfrogs** [comment]
Thanks however it is creating problems as the program uses a setup.py and using a dependency link from that fails to download.

**Comment by greenfrogs** [comment]
@marioidival what sort of time frame is there for an update to the python package index?

**Comment by marioidival** [comment]
@greenfrogs Today I do this. sorry to delay!

**Comment by marioidival** [comment]
@greenfrogs done! Thank you, verify now!

**Comment by greenfrogs** [comment]
@marioidival thanks it works!

**Comment by marioidival** [comment]
@greenfrogs i'll close this issue, thank you!
